name: Docker Hub Charts

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    name: Test Charts
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Test
        run: make test

      - name: Setup
        run: make integration-setup

      - name: Integration
        run: make integration-docker-hub

      - name: Describe
        if: ${{ failure() }}
        run: kubectl describe pods -n apps

      - name: Cleanup
        if: ${{ always() }}
        run: make integration-destroy
